---
- name: reboot vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  #pre_tasks:
  #  - include_vars: vars.yml
  tasks:
    - name: guest reboot
      vmware_guest_powerstate:
        hostname: "stg-m01-vc01.stg.local"
        username: "administrator@vsphere.local"
        password: "VxRai7$$2021!!"
        validate_certs: false
        name: "{{ vm_name }}"
        state: reboot-guest
        state_change_timeout: 120
      register: reboot
      ignore_errors: true
    - name: reboot
      vmware_guest_powerstate:
        hostname: "stg-m01-vc01.stg.local"
        username: "administrator@vsphere.local"
        password: "VxRai7$$2021!!"
        validate_certs: false
        name: "{{ vm_name }}"
        state: reboot-guest
      when: reboot.failed
