---
- name: start vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  #pre_tasks:
  #  - include_vars: vars-vmstart.yml
  tasks:
    - name: guest start
      vmware_guest_powerstate:
        hostname: "{{ vC }}"
        username: "{{ vCuser }}"
        password: "{{ vCpwd }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: powered-on
        state_change_timeout: 120
      register: poweredon
      ignore_errors: true
    - name: poweron
      vmware_guest_powerstate:
        hostname: "{{ vC }}"
        username: "{{ vCuser }}"
        password: "{{ vCpwd }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: powered-on
      when: poweredon.failed
