---
- name: stop vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
 # pre_tasks:
 #   - include_vars: vars.yml
  tasks:
    - name: guest shutdown
      vmware_guest_powerstate:
        hostname: "stg-m01-vc01.stg.local"
        username: "administrator@vsphere.local"
        password: "VxRai7$$2021!!"
        validate_certs: false
        name: "{{ host_group }}"
        state: shutdown-guest
        state_change_timeout: 120
      register: shutdown
      ignore_errors: true
    - name: poweroff
      vmware_guest_powerstate:
        hostname: "stg-m01-vc01.stg.local"
        username: "administrator@vsphere.local"
        password: "VxRai7$$2021!!"
        validate_certs: false
        name: "{{ host_group }}"
        state: powered-off
      when: shutdown.failed
